// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto-submit-controller"
application.register("auto-submit", AutoSubmitController)

import ClearFormController from "./clear-form-controller"
application.register("clear-form", ClearFormController)
